# Generated by Django 4.2.9 on 2025-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_date_order_ordered_at_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Karta kredytowa'), ('paypal', 'PayPal'), ('bank_transfer', 'Przelew bankowy')], max_length=50),
        ),
    ]
